apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apigateway
  template:
    metadata:
      labels:
        name: apigateway
    spec:
      containers:
      - image: reimbursementpoccontainerregistry.azurecr.io/gateway-api
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Dev"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:80"
        - name: GlobalConfiguration__Hosts__AdministrationAPI
          value: "http://administration"
        - name: GlobalConfiguration__Hosts__VendorAPI
          value: "http://vendor"
        - name: GlobalConfiguration__Hosts__CustomerAPI
          value: "http://customer"
        # - name: GlobalConfiguration__BaseUrl
          # value: "http://52.224.186.68"
        - name: IdentityAPI
          value: "https://identity:443"
        name: apigateway
        ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: apigateway
    labels:
      name: apigateway
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 80
      protocol: TCP
    selector:
        name: apigateway