apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: identity
  name: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      name: identity
  template:
    metadata:
      labels:
        name: identity
    spec:
      containers:
        - image: reimbursementpoccontainerregistry.azurecr.io/identity-api
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Dev"
          - name: ASPNETCORE_URLS
            value: "https://0.0.0.0:443"
          - name: ConnectionStrings__Db
            value: "REPLACEConnectionStrings__DbREPLACE"
          name: vendor
          ports:
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: identity
  labels:
    name: identity
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  type: LoadBalancer
  selector:
    name: identity