apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apigateway
  template:
    metadata:
      labels:
        name: apigateway
    spec:
      containers:
      - image: reimbursementpoccontainerregistry.azurecr.io/gateway-api
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "QA"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:80"
        - name: GlobalConfiguration__Hosts__AdministrationAPI
          value: "http://administration"
        - name: GlobalConfiguration__Hosts__VendorAPI
          value: "http://vendor"
        - name: GlobalConfiguration__Hosts__CustomerAPI
          value: "http://customer"
        - name: GlobalConfiguration__BaseUrl
          value: "http://52.224.186.68"
        - name: IdentityAPI
          value: "https://ri-identity-api627w7ovra6cy4.azurewebsites.net"
        name: apigateway
        ports:
         - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: administration
  name: administration
spec:
  replicas: 1
  selector:
    matchLabels:
      name: administration
  template:
    metadata:
      labels:
        name: administration
    spec:
      containers:
        - image: reimbursementpoccontainerregistry.azurecr.io/administration-api
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "QA"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:80"
          - name: ConnectionStrings__EventBus
            value: "Endpoint=sb://ri-event-bussu445yrz7ulry.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dJCSxV2gLaq8zYtpuvH+ujWXvKfqs/TF9+ASbGrKWy0="
          - name: ConnectionStrings__Db
            value: "Server=tcp:reimbursementpocsql-627w7ovra6cy4.database.windows.net,1433;Initial Catalog=administrationdb2;Persist Security Info=False;User ID=riadmin;Password=ri@admin78@9#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          name: administration
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: customer
  name: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      name: customer
  template:
    metadata:
      labels:
        name: customer
    spec:
      containers:
        - image: reimbursementpoccontainerregistry.azurecr.io/customer-api
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "QA"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:80"
          - name: ConnectionStrings__EventBus
            value: "Endpoint=sb://ri-event-bussu445yrz7ulry.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dJCSxV2gLaq8zYtpuvH+ujWXvKfqs/TF9+ASbGrKWy0="
          - name: ConnectionStrings__Db
            value: "Server=tcp:reimbursementpocsql-627w7ovra6cy4.database.windows.net,1433;Initial Catalog=customerdb;Persist Security Info=False;User ID=riadmin;Password=ri@admin78@9#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          name: customer
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: vendor
  name: vendor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vendor
  template:
    metadata:
      labels:
        name: vendor
    spec:
      containers:
        - image: reimbursementpoccontainerregistry.azurecr.io/vendor-api
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "QA"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:80"
          - name: ConnectionStrings__EventBus
            value: "Endpoint=sb://ri-event-bussu445yrz7ulry.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dJCSxV2gLaq8zYtpuvH+ujWXvKfqs/TF9+ASbGrKWy0="
          - name: ConnectionStrings__Db
            value: "Server=tcp:reimbursementpocsql-627w7ovra6cy4.database.windows.net,1433;Initial Catalog=vendordb;Persist Security Info=False;User ID=riadmin;Password=ri@admin78@9#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          name: vendor
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: apigateway
    labels:
      name: apigateway
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    selector:
        name: apigateway
---
apiVersion: v1
kind: Service
metadata:
  name: administration
  labels:
    name: administration
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    name: administration  
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    name: customer
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    name: customer
---
apiVersion: v1
kind: Service
metadata:
  name: vendor
  labels:
    name: vendor
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    name: vendor