version: '3.4'

services:
  apigateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443
      - GlobalConfiguration__BaseUrl: https://apigateway.api  
      - GlobalConfiguration__Hosts__AdministrationAPI: http://administration.api
      - GlobalConfiguration__Hosts__VendorAPI: http://vendor.api
      - GlobalConfiguration__Hosts__CustomerAPI: http://customer.api
      - BaseUrl: https://ri.apigateway.api  
    ports:
      - "8501:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  administration.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ConnectionStrings__Db=Server=administration.sqldata;Database=administration;User Id=sa;Password=Pass@word
      - ConnectionStrings__EventBus=Endpoint=sb://ri-event-bussu445yrz7ulry.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dJCSxV2gLaq8zYtpuvH+ujWXvKfqs/TF9+ASbGrKWy0=
      - ConnectionStrings__EventBus=Endpoint=ri-event-bus-sc2
    ports:
      - "8501:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - administration.sqldata
      
  administration.sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - pa-sqldata:/var/opt/mssql
      
  customer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ConnectionStrings__Db=Server=customer.sqldata;Database=administration;User Id=sa;Password=Pass@word
      - ConnectionStrings__EventBus=Endpoint=sb://ri-event-bussu445yrz7ulry.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dJCSxV2gLaq8zYtpuvH+ujWXvKfqs/TF9+ASbGrKWy0=
      - ConnectionStrings__EventBus=Endpoint=ri-event-bus-sc2
    ports:
      - "8502:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - customer.sqldata

  customer.sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - pa-sqldata:/var/opt/mssql
      
  vendor.api:
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:80
      - ConnectionStrings__Db=Server=vendor.sqldata;Database=administration;User Id=sa;Password=Pass@word
      - ConnectionStrings__EventBus=Endpoint=sb://ri-event-bussu445yrz7ulry.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dJCSxV2gLaq8zYtpuvH+ujWXvKfqs/TF9+ASbGrKWy0=
      - ConnectionStrings__EventBus=Endpoint=ri-event-bus-sc2
      - UiUrl=https://localhost:7231
    ports:
      - "8503:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - vendor.sqldata
      
  vendor.sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5435:1433"
    volumes:
      - pa-sqldata:/var/opt/mssql
      
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443
      - ConnectionStrings__DefaultConnection=identity.sqldata;Database=administration;User Id=sa;Password=Pass@word
      - ConnectionStrings__EventBus=Endpoint=sb://ri-event-bussu445yrz7ulry.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=dJCSxV2gLaq8zYtpuvH+ujWXvKfqs/TF9+ASbGrKWy0=
      - ConnectionStrings__EventBus=Endpoint=ri-event-bus-sc2
    ports:
      - "8504:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - identity.sqldata
      
  identity.sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5436:1433"
    volumes:
      - pa-sqldata:/var/opt/mssql
      
  rabbitmq:
     image: rabbitmq:3-management-alpine
     ports:
       - "15672:15672"
       - "5672:5672"
volumes:
  pa-sqldata:
    external: false

