#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["Sevices/Customer/ReimbursementPoC.Customer.API/ReimbursementPoC.Customer.API.csproj", "Sevices/Customer/ReimbursementPoC.Customer.API/"]
COPY ["Sevices/Customer/ReimbursementPoC.Customer.Application/ReimbursementPoC.Customer.Application.csproj", "Sevices/Customer/ReimbursementPoC.Customer.Application/"]
COPY ["Infrastructure/EventBusServiceBus/ReimbursementPoC.Infrustructure.EventBusServiceBus.csproj", "Infrastructure/EventBusServiceBus/"]
COPY ["Infrastructure/EventBus/ReimbursementPoC.Infrustructure.EventBus.csproj", "Infrastructure/EventBus/"]
COPY ["Sevices/Customer/ReimbursementPoC.Customer.Domain/ReimbursementPoC.Customer.Domain.csproj", "Sevices/Customer/ReimbursementPoC.Customer.Domain/"]
COPY ["Sevices/Customer/ReimbursementPoC.Customer.Infrastructure/ReimbursementPoC.Customer.Infrastructure.csproj", "Sevices/Customer/ReimbursementPoC.Customer.Infrastructure/"]
RUN dotnet restore "Sevices/Customer/ReimbursementPoC.Customer.API/ReimbursementPoC.Customer.API.csproj"

COPY . .

WORKDIR "/src/Sevices/Customer/ReimbursementPoC.Customer.API"
RUN dotnet build "ReimbursementPoC.Customer.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ReimbursementPoC.Customer.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "ReimbursementPoC.Customer.API.dll"]