apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: administration
  name: administration
spec:
  replicas: 1
  selector:
    matchLabels:
      name: administration
  template:
    metadata:
      labels:
        name: administration
    spec:
      containers:
        - image: "reimbursementpoccontainerregistry.azurecr.io/administration-api"
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:80"
          - name: ConnectionStrings__Db
            value: "REPLACEConnectionStrings__DbREPLACE"
          - name: ASB_Connection_String
            value: "REPLACEASB_Connection_StringREPLACE"
          name: administration
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: administration
  labels:
    name: administration
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    name: administration