variables:
  ConnectedServiceName: '6cf3b32b-192f-4368-be07-e65c36cb08da'
  WebAppKind: 'webAppLinux'
  WebAppName: 'riangularuiWebApp'
  StartupCommand: 'pm2 serve /home/site/wwwroot --no-daemon --spa'

steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: '$(Parameters.ConnectedServiceName)'
    appType: '$(Parameters.WebAppKind)'
    WebAppName: '$(Parameters.WebAppName)'
    StartupCommand: '$(Parameters.StartupCommand)'
    WebConfigParameters: '-Handler iisnode -NodeStartFile server.js -appType node'
    AppSettings: '-WEBSITE_NODE_DEFAULT_VERSION 6.9.1'
