steps:
- task: KubernetesManifest@1
  displayName: createSecret
  inputs:
    action: createSecret
    kubernetesServiceConnection: 'aks_connection'
    secretName: 'reimbursementpoccontainerregistrycr170491e0-auth'
    dockerRegistryEndpoint: 'acr_connection'
steps:
- task: KubernetesManifest@1
  displayName: deploy
  inputs:
    kubernetesServiceConnection: 'aks_connection'
    manifests: '$(System.DefaultWorkingDirectory)/*/manifests/apigateway.yml'
    containers: 'reimbursementpoccontainerregistry.azurecr.io/gateway-api:$(Build.BuildNumber)'
    imagePullSecrets: 'reimbursementpoccontainerregistrycr170491e0-auth'

