parameters:
- name: resourceGroupName
  type: boolean
  default: 'ri-poc-rg'
pool:
  name: Azure Pipelines
steps:
- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'Visual Studio Professional с подпиской MSDN (404aea7e-eb4e-4ac8-9314-08837b50d1cb)'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'az group create --n {{ parameters.resourceGroupName }} -l eastus'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Professional с подпиской MSDN (404aea7e-eb4e-4ac8-9314-08837b50d1cb)'
    action: 'Create Or Update Resource Group'
    subscriptionId: '404aea7e-eb4e-4ac8-9314-08837b50d1cb'
    resourceGroupName: '{{ parameters.resourceGroupName }}'
    location: 'eastus2'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/vnet.json'    
    deploymentMode: 'Incremental'
