parameters:
  name: '' 
  vmImage: ''
  displayName: ''
  resourceGroupName: 'ri-poc-rg'
  
pool:
  name: Azure Pipelines
steps:
- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'Visual Studio Professional с подпиской MSDN (404aea7e-eb4e-4ac8-9314-08837b50d1cb)'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: 'az group create --n {{ parameters.resourceGroupName }} -l eastus'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: 'Visual Studio Professional с подпиской MSDN (404aea7e-eb4e-4ac8-9314-08837b50d1cb)'
    subscriptionId: '404aea7e-eb4e-4ac8-9314-08837b50d1cb'
    resourceGroupName: {{ parameters.resourceGroupName }}
    location: 'Australia Central 2'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/rg.json'
