#Your build pipeline references an undefined variable named ‘dbIdentityConnectionString’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- script: |
   echo Write your commands here
   
   echo Old file
   cat '$(System.DefaultWorkingDirectory)/_ReimbursementPoC.Identity.API build azure pipelines/manifests/identity.yml'
   
   sed -i 's/REPLACEConnectionStrings__DbREPLACE/$(dbIdentityConnectionString)/'  '$(System.DefaultWorkingDirectory)/_ReimbursementPoC.Identity.API build azure pipelines/manifests/identity.yml'
   
   echo Updated file
   cat '$(System.DefaultWorkingDirectory)/_ReimbursementPoC.Identity.API build azure pipelines/manifests/identity.yml'
  displayName: 'Command Line Script'

- task: KubernetesManifest@1
  displayName: createSecret
  inputs:
    action: createSecret
    kubernetesServiceConnection: 'aks_connection'
    secretName: 'reimbursementpoccontainerregistrycr170491e0-auth'
    dockerRegistryEndpoint: 'acr_connection'
steps:
- task: KubernetesManifest@1
  displayName: deploy
  inputs:
    kubernetesServiceConnection: 'aks_connection'
    manifests: '$(System.DefaultWorkingDirectory)/*/manifests/identity.yml'
    containers: 'reimbursementpoccontainerregistry.azurecr.io/identity-api:$(Build.BuildNumber)'
    imagePullSecrets: 'reimbursementpoccontainerregistrycr170491e0-auth'

