variables:
  ConnectedServiceName: 'a2b260d0-3adc-4817-9880-9b5f3e910ab1'
  WebAppKind: 'webApp'
  WebAppName: 'ri-identity-api'

steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: '$(Parameters.ConnectedServiceName)'
    appType: '$(Parameters.WebAppKind)'
    WebAppName: '$(Parameters.WebAppName)'
    packageForLinux: '$(System.DefaultWorkingDirectory)/_ReimbursementPoC.Identity.API build azure pipelines/drop/ReimbursementPoC.Identity.API.zip'