pool:
  name: Azure Pipelines

variables:
- group: dev-variable-group
- name: resourceGroupName
  value: 'ri-poc-rg'
- name: location
  value: 'eastus2'

steps:
- task: AzureCLI@2
  displayName: 'Resource group'
  inputs:
    azureSubscription: $(arm_connection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'az group create --n ri-poc-rg -l eastus'
    
- task: AzureCLI@2
  displayName: 'Container registry'
  inputs:
    azureSubscription: $(arm_connection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'az acr create --resource-group $(resourceGroupName) --name reimbursementpoccontainerregistry --sku Basic'
   
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Storage'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(arm_connection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/deploystorage.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/deploystorage.parameters.json'   
    deploymentMode: 'Incremental'  
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Service bus'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(arm_connection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/sbusdeploy.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/sbusdeploy.parameters.json'   
    deploymentMode: 'Incremental'
    deploymentOutputs: servicebustemplateoutput

- pwsh: |
    $armOutputObj = '$(servicebustemplateoutput)' | convertfrom-json
    $connectionString = $armOutputObj.namespaceConnectionString.value
    Write-Output "##vso[task.setvariable variable=serviceBusConn;issecret=true;]$connectionString"
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: SQL'
  inputs:
    deploymentScope: 'Resource Group'    
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(arm_connection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/sqldeploy.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/sqldeploy.parameters.json'
    deploymentMode: 'Incremental'
    overrideParameters: '-al $(sqlAdminLogin) -alp $(sqlAdminPassword)'
    deploymentOutputs: sqltemplateoutput
    

- pwsh: |
    $armOutputObj2 = '$(sqltemplateoutput)' | convertfrom-json
    $sqlServerName1 = $armOutputObj2.sqlServerName.value
    Write-Output "##vso[task.setvariable variable=sqlServerName;issecret=true;]$sqlServerName1"
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Cosmos Db'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(arm_connection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/deploycosmos.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/deploycosmos.parameters.json'   
    deploymentMode: 'Incremental'


- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Key Vault'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(arm_connection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/keyvault.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/keyvault.parameters.json'   
    deploymentMode: 'Incremental'
    overrideParameters: '-serviceBusConnectionString $(serviceBusConn) -sqlServerName $(sqlServerName) -sqlAdminLogin $(sqlAdminLogin) -sqlAdminPassword $(sqlAdminPassword)'
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: App service - UI'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(arm_connection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/deloy-app-service-linux.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/deloy-app-service-ui.parameters.json'   
    deploymentMode: 'Incremental'
    # overrideParameters: '-subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -location $(location) -serverFarmResourceGroup $(resourceGroupName)'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: App service - Blazor UI'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(arm_connection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/deloy-app-service-windows.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/deloy-app-service-blazor-ui.parameters.json'   
    deploymentMode: 'Incremental'
    # overrideParameters: '-subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -location $(location) -serverFarmResourceGroup $(resourceGroupName)'
 
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Redis'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(arm_connection)
    action: 'Create Or Update Resource Group'
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/redisdeploy.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/redisdeploy.parameters.json'   
    deploymentMode: 'Incremental'
    
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: K8S'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(arm_connection)
    action: 'Create Or Update Resource Group'
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/aksdeploy.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/aksdeploy.parameters.json'   
    deploymentmode: 'incremental'
    overrideparameters: ''

    
 # - task: AzureCLI@2
   # displayName: 'K8S'
   # inputs:
     # azureSubscription: 'Visual Studio Professional с подпиской MSDN (404aea7e-eb4e-4ac8-9314-08837b50d1cb)'
     # scriptType: bash
     # scriptLocation: inlineScript
     # inlineScript: 'az aks create --resource-group reimbursement-poc-rg --name reimbursement-poc --node-count 1 --enable-addons monitoring --generate-ssh-keys  --node-vm-size Standard_B2s'

