pool:
  name: Azure Pipelines

variables:
  azureResourceManagerConnection: 'Visual Studio Professional с подпиской MSDN (404aea7e-eb4e-4ac8-9314-08837b50d1cb)'
  azureSubscription: 'Visual Studio Professional с подпиской MSDN (404aea7e-eb4e-4ac8-9314-08837b50d1cb)'
  subscriptionId: '404aea7e-eb4e-4ac8-9314-08837b50d1cb'
  resourceGroupName: 'ri-poc-rg'
  location: 'eastus2'

steps:
- task: AzureCLI@2
  displayName: 'Resource group'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'az group create --n ri-poc-rg -l eastus'
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: SQL'
  inputs:
    deploymentScope: 'Resource Group'    
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/sqldeploy.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/sqldeploy.parameters.json'
    deploymentMode: 'Incremental'
    overrideParameters: '-al $(adminLogin) -alp $(adminLogin)'
    deploymentOutputs: sqltemplateoutput

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: App service - Idenytity API'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/deloy-app-service.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/deloy-app-service-identity-api.parameters.json'   
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: App service - UI'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/deloy-app-service.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/deloy-app-service-ui.parameters.json'   
    deploymentMode: 'Incremental'
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Cosmos Db'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/deploycosmos.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/deploycosmos.parameters.json'   
    deploymentMode: 'Incremental'
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Storage'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/deploystorage.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/deploystorage.parameters.json'   
    deploymentMode: 'Incremental'
    
# - task: AzureResourceManagerTemplateDeployment@3
  # displayName: 'ARM Template deployment: Redis'
  # inputs:
    # deploymentScope: 'Resource Group'
    # azureResourceManagerConnection: 'Visual Studio Professional с подпиской MSDN (404aea7e-eb4e-4ac8-9314-08837b50d1cb)'
    # action: 'Create Or Update Resource Group'
    # subscriptionId: '404aea7e-eb4e-4ac8-9314-08837b50d1cb'
    # resourceGroupName: 'ri-poc-rg'
    # location: 'eastus2'
    # templateLocation: 'Linked artifact'
    # csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/redisdeploy.json' 
    # csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/redisdeploy.parameters.json'   
    # deploymentMode: 'Incremental'
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Service bus'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/sbusdeploy.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/sbusdeploy.parameters.json'   
    deploymentMode: 'Incremental'
    deploymentOutputs: servicebustemplateoutput

- pwsh: |
    $armOutputObj = '$(servicebustemplateoutput)' | convertfrom-json
    $connectionString = $armOutputObj.namespaceConnectionString.value
    Write-Output "##vso[task.setvariable variable=serviceBusConn;issecret=true;]$connectionString"
    
- pwsh: |
    $armOutputObj2 = '$(sqltemplateoutput)' | convertfrom-json
    $sqlServerName1 = $armOutputObj2.sqlServerName.value
    $sqlAdminLogin1 = $armOutputObj2.sqlAdminLogin.value
    $sqlAdminPassword1 = $armOutputObj2.sqlAdminPassword.value
    Write-Output "##vso[task.setvariable variable=sqlServerName;issecret=true;]$sqlServerName1"
    Write-Output "##vso[task.setvariable variable=sqlAdminLogin;issecret=true;]$sqlAdminLogin1"
    Write-Output "##vso[task.setvariable variable=sqlAdminPassword;issecret=true;]$sqlAdminPassword1"

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Key Vault'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/keyvault.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/keyvault.parameters.json'   
    deploymentMode: 'Incremental'
    overrideParameters: '-serviceBusConnectionString $(serviceBusConn) -sqlServerName $(sqlServerName) -sqlAdminLogin $(sqlAdminLogin) -sqlAdminPassword $(sqlAdminPassword)'

- task: AzureCLI@2
  displayName: 'Container registry'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'az acr create --resource-group $(resourceGroupName) --name reimbursementpoccontainerregistry --sku Basic'
    
    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: K8S'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: $(azureResourceManagerConnection)
    subscriptionId: $(subscriptionId)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy/template/aksdeploy.json' 
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy/template/aksdeploy.parameters.json'   
    deploymentMode: 'Incremental'
    overrideParameters: ''

    
 # - task: AzureCLI@2
   # displayName: 'K8S'
   # inputs:
     # azureSubscription: 'Visual Studio Professional с подпиской MSDN (404aea7e-eb4e-4ac8-9314-08837b50d1cb)'
     # scriptType: bash
     # scriptLocation: inlineScript
     # inlineScript: 'az aks create --resource-group reimbursement-poc-rg --name reimbursement-poc --node-count 1 --enable-addons monitoring --generate-ssh-keys  --node-vm-size Standard_B2s'

